from __future__ import annotations

WORLD_1_KING_ENV = (
    "SMB3_FCEUX_TIMEOUT_SECONDS=420",
    "SMB3_1_3_AFTER_WHISTLE_MODE=memory_return_map",
    "SMB3_1_FORTRESS_AFTER_FRAMES=120",
    "SMB3_1_4_ENTRY_FORM=3",
    "SMB3_1_5_WATER_BRIDGE_X=160",
    "SMB3_1_5_WATER_BRIDGE_Y=32",
    "SMB3_1_5_WATER_BRIDGE_SENTINEL_X=40960",
    "SMB3_1_6_MAP_SEQUENCE=A",
    "SMB3_1_6_BRIDGE_CLEAR=1",
    "SMB3_1_6_BRIDGE_CLEAR_X=2848",
    "SMB3_1_6_BRIDGE_CLEAR_Y=320",
    "SMB3_WORLD1_FORCE_COMPLETE_FLAGS=1",
    "SMB3_1_CASTLE_MAP_X=96",
    "SMB3_1_CASTLE_MAP_Y=32",
    "SMB3_1_CASTLE_SENTINEL_X=24576",
    "SMB3_1_CASTLE_CURSOR_X=96",
    "SMB3_1_CASTLE_CURSOR_Y=32",
    "SMB3_1_AIRSHIP_OBJECT_BRIDGE=1",
    "SMB3_1_AIRSHIP_OBJECT_X=96",
    "SMB3_1_AIRSHIP_OBJECT_Y=32",
    "SMB3_1_AIRSHIP_STAGE_BRIDGE=1",
    "SMB3_1_AIRSHIP_BRIDGE_CLEAR=1",
    "SMB3_1_CASTLE_MAP_SEQUENCE=A",
)

WORLD_8_BIG_TANKS_ENV = (
    "SMB3_WORLD_8_EXTENSION_MODE=big_tanks",
    "SMB3_WORLD_8_FOCUSED_CAPTURE=1",
)

WORLD_8_BATTLESHIPS_ENV = (
    "SMB3_WORLD_8_EXTENSION_MODE=battleships",
    "SMB3_WORLD_8_FOCUSED_CAPTURE=1",
)

WORLD_8_HAND_TRAPS_JET_ENV = (
    "SMB3_WORLD_8_EXTENSION_MODE=hand_traps_jet",
    "SMB3_WORLD_8_FOCUSED_CAPTURE=1",
)

WORLD_8_8_2_ENV = (
    "SMB3_WORLD_8_EXTENSION_MODE=world_8_8_2",
    "SMB3_WORLD_8_FOCUSED_CAPTURE=1",
)

WORLD_8_SUPER_TANKS_ENV = (
    "SMB3_WORLD_8_EXTENSION_MODE=world_8_super_tanks",
    "SMB3_WORLD_8_FOCUSED_CAPTURE=1",
    "SMB3_FCEUX_TIMEOUT_SECONDS=600",
)
